import dotenv from 'dotenv';

dotenv.config();

export const env = {
	AWS_ACCESS_KEY_ID: process.env.AWS_ACCESS_KEY_ID,
	AWS_SECRET_ACCESS_KEY: process.env.AWS_SECRET_ACCESS_KEY,
	S3_USER_CONTENT_BUCKET: process.env.S3_USER_CONTENT_BUCKET,
	S3_USER_CONTENT_BUCKET_REGION: process.env.S3_USER_CONTENT_BUCKET_REGION,
	S3_USER_CONTENT_BUCKET_URL: process.env.S3_USER_CONTENT_BUCKET_URL,
	S3_USER_CONTENT_BUCKET_URL_PUBLIC: process.env.S3_USER_CONTENT_BUCKET_URL_PUBLIC,
};